import { simpleGit, SimpleGit } from 'simple-git';
import path from 'path';
import { promises as fs } from 'fs';

export interface CommitOptions {
  message: string;
  branch?: string;
  author?: {
    name: string;
    email: string;
  };
  files: string[];
}

export interface PullRequestOptions {
  title: string;
  body: string;
  baseBranch: string;
  headBranch: string;
}

export class CommitManager {
  private git: SimpleGit;
  private repoPath: string;

  constructor(repoPath: string) {
    this.repoPath = repoPath;
    this.git = simpleGit(repoPath);
  }

  async initializeRepository(cloneUrl: string, accessToken: string): Promise<void> {
    try {
      // Check if repository already exists
      const exists = await this.repositoryExists();

      if (!exists) {
        await this.cloneRepository(cloneUrl, accessToken);
      } else {
        await this.pullLatestChanges();
      }
    } catch (error) {
      console.error('Error initializing repository:', error);
      throw error;
    }
  }

  async createBranch(branchName: string): Promise<void> {
    try {
      await this.git.checkoutLocalBranch(branchName);
    } catch (error) {
      console.error(`Error creating branch ${branchName}:`, error);
      throw error;
    }
  }

  async switchToBranch(branchName: string): Promise<void> {
    try {
      await this.git.checkout(branchName);
    } catch (error) {
      console.error(`Error switching to branch ${branchName}:`, error);
      throw error;
    }
  }

  async stageFiles(files: string[]): Promise<void> {
    try {
      for (const file of files) {
        const fullPath = path.join(this.repoPath, file);

        // Check if file exists before staging
        try {
          await fs.access(fullPath);
          await this.git.add(file);
        } catch (error) {
          console.warn(`File ${file} does not exist, skipping`);
        }
      }
    } catch (error) {
      console.error('Error staging files:', error);
      throw error;
    }
  }

  async commitChanges(options: CommitOptions): Promise<string> {
    try {
      // Stage the specified files
      await this.stageFiles(options.files);

      // Set author if provided
      if (options.author) {
        await this.git.addConfig('user.name', options.author.name, false, 'local');
        await this.git.addConfig('user.email', options.author.email, false, 'local');
      }

      // Create the commit
      const result = await this.git.commit(options.message);

      return result.commit;
    } catch (error) {
      console.error('Error committing changes:', error);
      throw error;
    }
  }

  async pushChanges(branch?: string, force: boolean = false): Promise<void> {
    try {
      if (branch) {
        if (force) {
          await this.git.push('origin', branch, ['--force']);
        } else {
          await this.git.push('origin', branch);
        }
      } else {
        if (force) {
          await this.git.push(['origin', '--force']);
        } else {
          await this.git.push();
        }
      }
    } catch (error) {
      console.error('Error pushing changes:', error);
      throw error;
    }
  }

  async createCommitForDocumentationUpdate(
    updatedFiles: string[],
    changeDescription: string
  ): Promise<string> {
    const branchName = `gem/doc-update-${Date.now()}`;

    try {
      // Ensure we're on the main branch first
      await this.git.checkout('main');
      await this.pullLatestChanges();

      // Create a new branch
      await this.createBranch(branchName);

      // Commit the changes
      const commitHash = await this.commitChanges({
        message: `📝 Update documentation: ${changeDescription}\n\n🤖 Generated by Gem Agent\n\nFiles updated:\n${updatedFiles.map(f => `- ${f}`).join('\n')}`,
        branch: branchName,
        author: {
          name: 'Gem Agent',
          email: 'gem@gemdesk.ai'
        },
        files: updatedFiles
      });

      // Push the branch
      await this.pushChanges(branchName);

      return commitHash;
    } catch (error) {
      console.error('Error creating documentation commit:', error);
      throw error;
    }
  }

  async createPullRequest(options: PullRequestOptions): Promise<string> {
    // This would integrate with GitHub API to create a pull request
    // For now, we'll return the branch name
    console.log('Pull request would be created:', options);
    return options.headBranch;
  }

  async getFileChanges(filePath: string): Promise<{
    added: string[];
    modified: string[];
    deleted: string[];
  }> {
    try {
      const status = await this.git.status([filePath]);

      return {
        added: status.created,
        modified: status.modified,
        deleted: status.deleted
      };
    } catch (error) {
      console.error(`Error getting file changes for ${filePath}:`, error);
      return { added: [], modified: [], deleted: [] };
    }
  }

  async revertChanges(files: string[]): Promise<void> {
    try {
      for (const file of files) {
        await this.git.checkout(['HEAD', file]);
      }
    } catch (error) {
      console.error('Error reverting changes:', error);
      throw error;
    }
  }

  async getDiffSummary(fromCommit?: string, toCommit?: string): Promise<string> {
    try {
      const diff = await this.git.diff([fromCommit || 'HEAD~1', toCommit || 'HEAD']);
      return diff;
    } catch (error) {
      console.error('Error getting diff summary:', error);
      return '';
    }
  }

  async getBranchStatus(): Promise<{
    current: string;
    ahead: number;
    behind: number;
  }> {
    try {
      const status = await this.git.status();
      return {
        current: status.current || 'main',
        ahead: status.ahead || 0,
        behind: status.behind || 0
      };
    } catch (error) {
      console.error('Error getting branch status:', error);
      return { current: 'main', ahead: 0, behind: 0 };
    }
  }

  private async repositoryExists(): Promise<boolean> {
    try {
      await fs.access(path.join(this.repoPath, '.git'));
      return true;
    } catch {
      return false;
    }
  }

  private async cloneRepository(cloneUrl: string, accessToken: string): Promise<void> {
    const authenticatedUrl = this.addTokenToUrl(cloneUrl, accessToken);
    await this.git.clone(authenticatedUrl, this.repoPath);
  }

  private async pullLatestChanges(): Promise<void> {
    try {
      await this.git.pull('origin', 'main');
    } catch (error) {
      console.error('Error pulling latest changes:', error);
    }
  }

  private addTokenToUrl(url: string, token: string): string {
    const urlObj = new URL(url);
    urlObj.username = token;
    return urlObj.toString();
  }
}